---
abstract: 'Easy-to-use self-cleaning scratch space.'
author:
  - 'Jonathan Rockway, all rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Directory-Scratch
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 9999.12
  File::Spec: 0
  File::Temp: 0
  File::stat: 0
  Path::Class: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/directory-scratch.git
version: 0.15
x_authority: JROCKWAY
